In [6]:
import pandas as pd
import requests
import numpy as np

from bs4 import BeautifulSoup
import re

In [2]:
pd.set_option("display.max_colwidth", None) ## 출력 잘림 해결

In [11]:
df = pd.read_excel("../data/myfair_participation_message_2268.xlsx").dropna(how='all')
df.head(3)

        id  \
0  84746.0
1  84760.0
2  84799.0


In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 110 entries, 0 to 109
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id                 103 non-null    float64
 1   message            103 non-null    object
 2   process_state      54 non-null     object
 3   sender_email       102 non-null    object
 4   message_type       103 non-null    object
 5   participation_num  110 non-null    int64
dtypes: float64(1), int64(1), object(4)
memory usage: 5.3+ KB

# 전처리

In [13]:
def preprocess_html_message(html_text):
    if pd.isna(html_text):
        return ""  # 또는 NaN 유지하려면: return np.nan

    # BeautifulSoup으로 HTML 파싱
    soup = BeautifulSoup(html_text, "html.parser")

    # <br> 태그는 줄바꿈으로 대체
    for br in soup.find_all("br"):
        br.replace_with("\n")

    # 텍스트만 추출
    raw_text = soup.get_text(separator=" ", strip=True)

    # 공백 정리
    raw_text = re.sub(r'\s+', ' ', raw_text)

    return raw_text

In [14]:
df['message_clean'] = df['message'].apply(preprocess_html_message)

# 결과 출력
print(df[['message', 'message_clean']].head())

In [15]:
df = df.drop(index=range(98,105)) #98~104행 message가 nan

***

# 영문 번역: Helsinki-NLP (MarianMT) + HuggingFace Transformers

In [16]:
from transformers import MarianMTModel, MarianTokenizer

model_name = 'Helsinki-NLP/opus-mt-ko-en'
tokenizer = MarianTokenizer.from_pretrained(model_name)
model = MarianMTModel.from_pretrained(model_name)

def translate(text):
    tokens = tokenizer.prepare_seq2seq_batch([text], return_tensors="pt")
    translation = model.generate(**tokens)
    return tokenizer.decode(translation[0], skip_special_tokens=True)

C:\Users\jwoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\models\marian\tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

## 문장 분할 후 번역
: 문장 단위로 분할하기 위해 .(마침표), ?, !, \n 등을 기준으로 하자

In [17]:
# 문장 분할 함수
def split_into_sentences(text):
    if not text or not isinstance(text, str):
        return []
    # 마침표, 느낌표, 물음표 + 공백 기준 분리
    sentences = re.split(r'(?<=[.!?])\s+|\n', text.strip())
    return [s.strip() for s in sentences if s.strip()]

In [18]:
# 번역 함수
def translate_sentence_by_sentence(text):
    sentences = split_into_sentences(text)
    translated_sentences = []
    for sentence in sentences:
        tokens = tokenizer.prepare_seq2seq_batch([sentence], return_tensors="pt")
        translation = model.generate(**tokens)
        translated = tokenizer.decode(translation[0], skip_special_tokens=True)
        translated_sentences.append(translated)
    return " ".join(translated_sentences)

### 적용

In [19]:
# 첫 번째 메시지 텍스트
text = df.loc[0, 'message_clean']

# 테스트 번역
translated_text = translate_sentence_by_sentence(text)

print("원문:")
print(text)
print("\n번역 결과:")
print(translated_text)

C:\Users\jwoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:4106: FutureWarning:
`prepare_seq2seq_batch` is deprecated and will be removed in version 5 of HuggingFace Transformers. Use the regular
`__call__` method to prepare your inputs and targets.

Here is a short example:

model_inputs = tokenizer(src_texts, text_target=tgt_texts, ...)

If you either need to use different keyword arguments for the source and target texts, you should do two calls like
this:

model_inputs = tokenizer(src_texts, ...)
labels = tokenizer(text_target=tgt_texts, ...)
model_inputs["labels"] = labels["input_ids"]

See the documentation of your specific tokenizer for more details on the specific arguments to the tokenizer of choice.
For a more complete example, see the implementation of `prepare_seq2seq_batch`.

  warnings.warn(formatted_warning, FutureWarning)

원문:
안녕하세요, (고객 성함 직함)님. 마이페어에서 디자인 기획을 담당하고 있는 (마이페어 담당자명 호칭)입니다. 이번 RE+ 프로젝트를 담당하게 되어 인사드립니다. RE+ 독립부스 시공과 관련하여 업무 진행 일정, 예산, 디자인 업무 규정 에 대해 안내 드립니다. 1. 업무 진행 일정 구분 진행해야 하는 업무 담당기업 진행 적정일자 디자인 착수 계약 양사 업무 계약서 싸인 (고객사명)/마이페어 2025.04.08 부스 디자인 전시 제품 확정 및 컨셉전달 (고객사명) 2025.04.10 전시장 규정 확인 및 1차 디자인 마이페어 2025.04.22 디자인 수정 사항 협의 및 2차 디자인 (고객사명)/마이페어 2025.04.29 디자인 수정 사항 협의 및 3차 디자인 (고객사명)/마이페어 2025.05.08 디자인 확정 (고객사명)/마이페어 2025.05.15 확정 견적 전달 마이페어 2025.05.23 부스 시공 계약 체결 및 선급금 입금 (고객사명)/마이페어 2025.05.30 도면 작업 마이페어 2025.06.05 도면 제작 및 발주 마이페어 2025.06.17 **도면 신고 및 허가 마이페어 2025.06.19 싸인 그래픽 전달 (고객사명) 2025.06.19 싸인 그래픽 플랜 제작 및 발주 마이페어 2025.06.26 전시품 운송 전시 제품 물류 발송 (선적) (고객사명) 운송사 일정 안내 전시 제품 물류 발송 (항공) (고객사명) 운송사 일정 안내 부스 시공 및 감리 박람회 부스 시공 및 감리 진행 마이페어 2025.09.05 박람회 참가 부스 인계 및 전시품 디스플레이 진행 (고객사명) 2025.09.07 박람회 개최 *마이페어에서는 첫날만 상주 합니다. 전체 기간 상주를 원하시면 별도 비용이 발생됩니다. (고객사명) 2025.09.08 박람회 종료 박람회 종료 및 철거 마이페어 2025.09.11 잔금 지급 *박람회 종료 후 7일 이내 잔금을 지급해주시면 됩니다. (고객사명) 2025.09.18 2. 예산 안내 RE+ 부스 시공 예산을 참고하실 수 있도록, 유사한 환경에서 진행된 시공 사례를 공유드립니다. 아래는 HIMSS 2025에서 마이페어가 진행했던 Sonix Health 부스입니다. 해당 부스는 400sqft 규모 로, Las Vegas Venetian Hall에 위치했으며, 의료 소프트웨어 장비를 전시하는 리깅이 없는 목공 부스 로 시공되었습니다. ( (고객사명)의 부스가 위치한 Caesars forum 전시장은 천장이 낮아 리깅이 불가능한 구조입니다.) 시공 비용은 약 1억 2천5백만원이었으며, (고객사명) 부스 예산 검토에 참고하시면 좋을 것 같습니다. Caesars forum 전시장 전경 Sonix Health 부스 사진 3. 디자인 업무 규정 안내 확인서 마이페어는 업무 착수 전에 디자인 업무 규정 계약을 진행하고 있습니다. (고객사명)은 마이페어의 주요 고객이시기에, 선급금을 따로 요청드리지 않습니다만 디자인 업무 규정 안내 확인서 살펴보시고 서명 부탁드립니다. 추가로 궁금하신 사항이나 기타사항 연락주시기 바랍니다. 직통번호 : 070.4618.0079 (010.7665.4564) 감사합니다.

번역 결과:
Hello, sir. It's a design project in Maypere. I'd like to introduce you to this R+ project. We're going to show you the schedules, budgets, and design protocols for R+Independence. 1. The 2025th and 2025th of the year. The 2025th of the year. The 2025ths and 2025ths of the year. The 2025ths of the year. The 2025ths and 2025ths of the year. The 2025ths and 2025ths of the year. The 2025ths of the year. The 2025C. If you want to share the entire week, it's going to cost you a lot of money. I'd like you to give me the balance in seven days after the end of the 2025.09.08 Fair and the withdrawal of the Myperer 2025.09.11. ( Customer Mission) 2025.09.18 2. So I'm going to share with you a budget guide, R+ Booth, which has been done in a similar environment. Below is the Sonix Health Booth, who was running the Mypere at HlMSS 2025. The booth was located at Las Vegas Ventean Hall on a 400-sqft scale, and was built as a carpenter's booth with no ligging to display medical software equipment. The cost of construction was about 125 million dollars, and it's worth a little bit of research on the Booth budget. Photo by Sanix Health Booth 3. Myperer's working on a design policy contract before he starts to do it. (Current Mission) As the primary client of the Mypere, we don't ask for advance money, but we would like you to check the design rules and sign them. Please contact me for additional questions and other details. Direct number: 0.70.4618.0079 (010.7665.4564) Thank you.

In [20]:
# 문장 단위로 번역하는 함수 정의 (앞서 정의된 함수 재사용)
def translate_sentence_by_sentence(text):
    if pd.isna(text):
        return text
    sentences = re.split(r'(?<=[.!?])\s+', text.strip())
    translated_sentences = []
    for sentence in sentences:
        if sentence:
            tokens = tokenizer.prepare_seq2seq_batch([sentence], return_tensors="pt")
            translation = model.generate(**tokens)
            translated = tokenizer.decode(translation[0], skip_special_tokens=True)
            translated_sentences.append(translated)
    return ' '.join(translated_sentences)

# 전체 행에 대해 번역 수행
df['message_en'] = df['message_clean'].apply(translate_sentence_by_sentence)

In [21]:
df[['message_clean', 'message_en']]

,message_clean,message_en
0,"안녕하세요, (고객 성함 직함)님. 마이페어에서 디자인 기획을 담당하고 있는 (마이페어 담당자명 호칭)입니다. 이번 RE+ 프로젝트를 담당하게 되어 인사드립니다. RE+ 독립부스 시공과 관련하여 업무 진행 일정, 예산, 디자인 업무 규정 에 대해 안내 드립니다. 1. 업무 진행 일정 구분 진행해야 하는 업무 담당기업 진행 적정일자 디자인 착수 계약 양사 업무 계약서 싸인 (고객사명)/마이페어 2025.04.08 부스 디자인 전시 제품 확정 및 컨셉전달 (고객사명) 2025.04.10 전시장 규정 확인 및 1차 디자인 마이페어 2025.04.22 디자인 수정 사항 협의 및 2차 디자인 (고객사명)/마이페어 2025.04.29 디자인 수정 사항 협의 및 3차 디자인 (고객사명)/마이페어 2025.05.08 디자인 확정 (고객사명)/마이페어 2025.05.15 확정 견적 전달 마이페어 2025.05.23 부스 시공 계약 체결 및 선급금 입금 (고객사명)/마이페어 2025.05.30 도면 작업 마이페어 2025.06.05 도면 제작 및 발주 마이페어 2025.06.17 **도면 신고 및 허가 마이페어 2025.06.19 싸인 그래픽 전달 (고객사명) 2025.06.19 싸인 그래픽 플랜 제작 및 발주 마이페어 2025.06.26 전시품 운송 전시 제품 물류 발송 (선적) (고객사명) 운송사 일정 안내 전시 제품 물류 발송 (항공) (고객사명) 운송사 일정 안내 부스 시공 및 감리 박람회 부스 시공 및 감리 진행 마이페어 2025.09.05 박람회 참가 부스 인계 및 전시품 디스플레이 진행 (고객사명) 2025.09.07 박람회 개최 *마이페어에서는 첫날만 상주 합니다. 전체 기간 상주를 원하시면 별도 비용이 발생됩니다. (고객사명) 2025.09.08 박람회 종료 박람회 종료 및 철거 마이페어 2025.09.11 잔금 지급 *박람회 종료 후 7일 이내 잔금을 지급해주시면 됩니다. (고객사명) 2025.09.18 2. 예산 안내 RE+ 부스 시공 예산을 참고하실 수 있도록, 유사한 환경에서 진행된 시공 사례를 공유드립니다. 아래는 HIMSS 2025에서 마이페어가 진행했던 Sonix Health 부스입니다. 해당 부스는 400sqft 규모 로, Las Vegas Venetian Hall에 위치했으며, 의료 소프트웨어 장비를 전시하는 리깅이 없는 목공 부스 로 시공되었습니다. ( (고객사명)의 부스가 위치한 Caesars forum 전시장은 천장이 낮아 리깅이 불가능한 구조입니다.) 시공 비용은 약 1억 2천5백만원이었으며, (고객사명) 부스 예산 검토에 참고하시면 좋을 것 같습니다. Caesars forum 전시장 전경 Sonix Health 부스 사진 3. 디자인 업무 규정 안내 확인서 마이페어는 업무 착수 전에 디자인 업무 규정 계약을 진행하고 있습니다. (고객사명)은 마이페어의 주요 고객이시기에, 선급금을 따로 요청드리지 않습니다만 디자인 업무 규정 안내 확인서 살펴보시고 서명 부탁드립니다. 추가로 궁금하신 사항이나 기타사항 연락주시기 바랍니다. 직통번호 : 070.4618.0079 (010.7665.4564) 감사합니다.","Hello, sir. It's a design project in Maypere. I'd like to introduce you to this R+ project. We're going to show you the schedules, budgets, and design protocols for R+Independence. 1. The 2025th and 2025th of the year. The 2025th of the year. The 2025ths and 2025ths of the year. The 2025ths of the year. The 2025ths and 2025ths of the year. The 2025ths and 2025ths of the year. The 2025ths of the year. The 2025C. If you want to share the entire week, it's going to cost you a lot of money. I'd like you to give me the balance in seven days after the end of the 2025.09.08 Fair and the withdrawal of the Myperer 2025.09.11. ( Customer Mission) 2025.09.18 2. So I'm going to share with you a budget guide, R+ Booth, which has been done in a similar environment. Below is the Sonix Health Booth, who was running the Mypere at HlMSS 2025. The booth was located at Las Vegas Ventean Hall on a 400-sqft scale, and was built as a carpenter's booth with no ligging to display medical software equipment. The cost of construction was about 125 million dollars, and it's worth a little bit of research on the Booth budget. Photo by Sanix Health Booth 3. Myperer's working on a design policy contract before he starts to do it. (Current Mission) As the primary client of the Mypere, we don't ask for advance money, but we would like you to check the design rules and sign them. Please contact me for additional questions and other details. Direct number: 0.70.4618.0079 (010.7665.4564) Thank you."
1,"프로님 안녕하세요. (고객사명) (고객 성함)입니다. 1. 마이페어 메세지 수신 시 기존에는 회사 이메일도 도착하였는데, 현재 카카오톡 알림만 진행되는 것 같습니다. 별도의 조치를 취해야 하는지요? 2. 리깅이 불가한 전시장에서 진행한 디자인 예시 공유 가능하신지요. 3. 마이페어 회원 등급 혜택인 AI컨셉 시안 무료 건도 진행하면서 받을 수 있는지요? 회신 부탁드립니다. 감사합니다.","Hello, Mr. Pro. It's called the Customer Mission. 1. When they received the Myperer's message, they also arrived at the company emails, and we think they're doing all the Kakaoka notifications. Should we do something different? 2. It's the ability to share design examples in a display where there's no ligging. 3. Can you do free AI Conceptian, which is a rating benefit for the Maypere membership? Please return. Thank you."
2,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 아래와 같이 문의 사항에 대한 답변 드립니다. 1. 시스템 오류 관련 : 일시적인 시스템 오류가 있었던 것으로 보입니다. 현재 정상적으로 해결된 상태이며, 지금부터는 메일 알림이 정상 작동 될 예정입니다. 별도의 조치는 필요하지 않습니다. 2. 리깅이 불가한 전시장에서 진행한 디자인 예시 : 관련 자료는 별도 메시지로 안내드리겠습니다. 3. 서비스 관련 : 이번에 저희가 새롭게 런칭한 서비스입니다. (고객사명)은 NAVIGATOR 등급이셔서 최대 3장까지 제공 가능합니다. 필요하신 시점에 문의 주시면 더욱 상세한 안내와 AI컨셉 시안을 제공해 드리겠습니다. 안내드린 업무 진행 일정은 괜찮으실까요? 감사합니다.","Hello, sir. Myperire. Here's an answer to the question: 1. System error: it seems there was a temporary system error. This is a normal solution, and from now on, the email notifications are going to work. You don't have to do anything different. 2. A design example from a display where the League was not available: we're going to take you through a separate message. 3. Services related: this is our new launch service. (Current Mission) It's a NAVIGATOR rating, and it's available for up to three chapters. I'd like to give you a more detailed guide and an AI concept at the moment that you need. Are you sure you're gonna be okay with the progress you've given me? Thank you."
3,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 지난해 RE+와 AAPEX에 참가하셨을 때도 전시장 천장에 리깅이 불가했던 것으로 보입니다. RE+ 부스에 타워를 세우고, 타워에 행잉사인을 설치 AAPEX 오픈형으로 타워를 세워 로고와 메시지를 전달 그 외 리깅이 제한되는 전시장에서 마이페어가 진행했던 디자인 사례를 아래와 같이 공유드립니다. 리깅이 제한되는 경우, 타워 구조를 활용하는 디자인이 많이 적용됩니다. 첨부된 사례 참고 부탁드립니다. 감사합니다.","Hello, sir. Myperire. Last year, when you were at Le+ and AAPEX, it looks like there was no ligging on the ceiling. We set up a tower on the Le+ Booth, and we set up a walker on the tower, an open-ended AAPEX, and we share with you another design example that Myperer did on a display where the walking was limited. When it's limited, it's a lot of design to use the structure of the tower. Please take a look at the accompanying example. Thank you."
4,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 이전 안내 드린 메시지 관련 추가 확인한 부분이 있어서 메시지 이어서 드립니다. 1. Caesars forum 전시장 리깅 가능 여부 부스 배정 받으신 Caesars forum은 일반적인 전시장과는 달리 천장이 낮아 리깅을 하지 않는 경우가 많지만, 추가적으로 사례를 확인한 결과 완전히 불가능한 것은 아닌 것으로 보입니다. (얼마 전에 다녀 왔을 때도 리깅을 전혀 못 봤는데 사진들 찾아보니 더 있네요.....! 😂) 첨부된 이미지와 같이 리깅이 가능할 수 있으나, 천장이 낮아 리깅 구조물이 부스와 거의 맞닿을 정도로 가까운 형태가 될 수 있습니다. 다만, 리깅 가능 여부는 전시장 규정이 발표된 후에 정확하게 확인할 수 있으므로, 현재는 가능할 경우의 형태와 고려해야 할 요소를 미리 안내드리는 차원에서 공유드립니다. 또한, 미국에서 리깅을 설치하는 경우 아시겠지만 리깅만 전문으로 하는 테크니션의 인건비가 높아 최소 2,000만원~3,000만원 정도의 추가 비용이 발생할 수 있으므로, 비용 대비 효과가 적절할지 함께 검토해주시면 좋을 것 같습니다. 2. 부스 디자인 전략 미팅 제안 이번 전시 부스 디자인에 앞서 '부스 디자인 전략 미팅'을 제안드립니다. RE+, AAPEX 등 여러 전시를 운영하시면서 느끼셨던 아쉬웠거나 만족스러웠던 점을 바탕으로 새로운 부스 디자인에 어떻게 반영할지, (고객사명)의 전시 참가 목표를 최적화할 수 있는 방안이 무엇인지 등을 한 번 논의하면 좋을 것 같습니다. 업무 진행 일정, 디자인 전략 미팅 등에 대해 의견 회신 부탁드립니다! 감사합니다.","Hello, sir. Myperire. Thank you very much for this post because I have an additional confirmation of the previous message that I gave you. 1. Caesars Forum, who has been assigned by Booth to the former mayor of Caesars forum, often doesn't have a low ceiling, but an additional example shows that it's not completely impossible. I didn't see anything going on when I was there, but when I looked up the photos, I saw more. like an image that's attached, but the ceiling is low, and the ligging structure can be close enough to the booth. But whether or not you can do it is precisely after the exhibition regulations have been published, so now we share them with you on a level that gives you a possible form and a pre-existing consideration. Also, if you're setting up a run in the U.S., as you know, there's a high cost of ligging-only technology, which can cost at least 20 to 30 million dollars, so you might want to check with them if the cost ratio works. 2. Booth's Design Strategy Meeting, and before we design this show, I'd like to propose the Bush Design Strategy Meeting. I think it's good to discuss how you can reflect on the design of the new booth, based on the fact that you've been running lots of exhibits like Le+, AAPEX, and so forth, and so forth. We'd like you to hear from us about our work schedule, our design strategy meeting, and so forth. Thank you."
...,...,...
105,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 1. 잔금 송금증 확인 안내 송금증 전달 감사드립니다. 주최측 재무팀에 입금 확인 요청하여 확인 처리 받겠습니다. 2. 부스 디자인 안내 내일 중으로 내부에서 일정 잡고 안내 드릴 수 있도록 하겠습니다! 감사합니다.","Hello, sir. Myperire. 1. I want to thank you for the tip check. I'm going to ask your financial team to sign up for a deposit, and we're going to check it out. 2. Booth's Design Guide, we'll get you a schedule from the inside tomorrow and give you a tour! Thank you."
106,프로님 안녕하세요. (고객사명) (고객 성함)입니다. RE+ 박람회장 홍보비용 안내 부탁드립니다. 실내 홍보비 (기둥 광고) 등,"Hello, Mr. Pro. It's called the Customer Mission. Let me show you the cost of public relations at the R+ Fair. Indoor promotions, and so forth."
107,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 스폰서쉽 상품 URL 공유 드립니다. 베네치안/시저스 포럼 별로 배너 상품들이 있습니다. 각 배너 상품 별 위치를 보신 후, 관심 있으신 상품의 이름을 말씀해주시면 금액 확인해서 안내 드리겠습니다. ▶스폰서쉽 상품 바로가기: https://envision.freeman.com/show/re-september-2025/home (금액이 오픈 되어 있지 않아서, 별도 문의를 통해 확인 받아야 하는 점 참고 부탁드립니다.) 감사합니다.","Hello, sir. Myperire. I'm sharing your sponsorship product with you. Venecchian/Syssers Forum has a lot of Banner goods. Look at the positions of each Banner product, and tell me the names of the goods you're interested in, and I'll show you the money. → Go straight to the sponsorship product: https: / /enviion.freeman.com/sh/re-september-2025/ home."
108,"프로님 안녕하세요. (고객사명) (고객 성함)입니다. 저 궁금한게 있습니다. 저희가 현재 수출바우처 모집공고에 신청하고자 하는데, 혹시 RE+ 전시회 부스관련하여 수출바우처 선정 시 당사부담에서 -> 수출바우처 전환이 가능한지요 회신 부탁드립니다. 감사합니다.","Hello, Mr. Pro. It's called the Customer Mission. I have a question. We're going to apply to the export pool now, but I would like to ask you if you're going to be able to transfer export from your commission to the R+ exhibition booth. Thank you."
109,"안녕하세요, (고객 성함 직함)님. 마이페어 (마이페어 담당자명 호칭)입니다. 결론적으로만 말씀 드리면 가능합니다! 수출바우처 계약기간 내에 RE+ 전시기간이 포함되어 있으면 됩니다. 사후정산 받으시면 부스비를 정산 받으실 수 있습니다. 마이페어가 미리 선납하고 사후정산 청구하는 방법도 있으나, 현재 *수임한도 제한으로 사후정산으로 밖에 안내를 드리지 못하는 점 양해 부탁드립니다. (회사 매출 대비 수임한도가 제한이 되는데, 현재 한도가 모두 달성된 상태여서 기관과 한도 상향 논의 중에 있습니다. 안될 가능성도 있기에 사후정산 안내드립니다.) 감사합니다.","Hello, sir. Myperire. In conclusion, it's possible! You just have to have a R+ period in the export process. If you receive an afterlife, you can get a bubby. Mafere has a pre-existing and post-mortal birth claim, but please excuse me for not being able to guide you outside to post-mortal acid with a limit on your presence. We're running out of time for the company's sales, and we're talking to the agency about the level, because we've got all the limits. Thank you."

In [22]:
# !pip install openpyxl

# 엑셀 파일로 저장
df.to_excel("translated_messages_2268.xlsx", index=False)

***

# LLaMA 영작: Hugging Face의 LLaMA 파생 모델 활용
- ⚠️ 주의: meta-llama/Llama-2-7b-chat-hf 모델은 Hugging Face에서 사용하려면 Hugging Face 계정으로 Meta의 사용 승인 요청 후, access token을 발급받아야 함
- 🤖 meta-llama/Llama-2-7b-chat-hf 모델은 Hugging Face에서 로그인하고 토큰 허용 권한을 수동으로 부여해야 사용할 수 있는 접근 제한 모델
- LLaMA 모델들은 접근 승인이 필요한 gated model
  - GPU가 없거나 사양이 낮은 경우 로딩 자체가 오래 걸리거나 실패할 수 있다

!pip install accelerate

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, pipeline

model_name = "meta-llama/Llama-2-7b-chat-hf"
token = "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"  # 여기에 복사한 토큰 붙여넣기

tokenizer = AutoTokenizer.from_pretrained(model_name, token=token)
model = AutoModelForCausalLM.from_pretrained(model_name, token=token, device_map="auto", torch_dtype="auto")

pipe = pipeline("text-generation", model=model, tokenizer=tokenizer)
print(pipe("Hello, I'm a llama model!", max_new_tokens=50))

model.safetensors.index.json:   0%|          | 0.00/26.8k [00:00<?, ?B/s]

C:\Users\jwoo\AppData\Local\Programs\Python\Python312\Lib\site-packages\huggingface_hub\file_download.py:143: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\jwoo\.cache\huggingface\hub\models--meta-llama--Llama-2-7b-chat-hf. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate developer mode, see this article: https://docs.microsoft.com/en-us/windows/apps/get-started/enable-your-device-for-development
  warnings.warn(message)

Fetching 2 files:   0%|          | 0/2 [00:00<?, ?it/s]

model-00002-of-00002.safetensors:   0%|          | 0.00/3.50G [00:00<?, ?B/s]

model-00001-of-00002.safetensors:   0%|          | 0.00/9.98G [00:00<?, ?B/s]

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]

- 🤖 Hugging Face transformers 라이브러리에서 필요한 클래스 불러오기
- 🔐 접근 제한 모델(LLaMA 2) 은 Hugging Face에서 접근 권한을 승인받고, 토큰을 붙여야 다운로드 가능
- 🧠 사전학습된 LLaMA 모델과 토크나이저를 로드

!pip install transformers huggingface_hub

In [12]:
from huggingface_hub import login

login(token="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")

In [ ]:
from transformers import AutoModelForCausalLM, AutoTokenizer
import torch

# 모델 및 토크나이저 로드
model_name = "meta-llama/Llama-2-7b-chat-hf"
model = AutoModelForCausalLM.from_pretrained(model_name)
tokenizer = AutoTokenizer.from_pretrained(model_name)

# 입력 텍스트 설정
input_text = "안녕하세요! 오늘 날씨 어때요?"

# 입력을 토큰화하고 모델에 전달
inputs = tokenizer(input_text, return_tensors="pt")

# 모델에 대한 출력 생성
with torch.no_grad():
    outputs = model.generate(inputs['input_ids'], max_length=50)

# 출력 텍스트 생성
generated_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
print(generated_text)

Loading checkpoint shards:   0%|          | 0/2 [00:00<?, ?it/s]